worker_processes 1;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    client_body_temp_path /tmp/nginx_client_body;
    proxy_temp_path /tmp/nginx_proxy;
    fastcgi_temp_path /tmp/nginx_fastcgi;
    uwsgi_temp_path /tmp/nginx_uwsgi;
    scgi_temp_path /tmp/nginx_scgi;

    server {
        listen 3900;

        location /v2/ {
            proxy_pass http://127.0.0.1:3903;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://127.0.0.1:3905;
            proxy_set_header Host $host;
        }
    }
}
